---
- name: Create temporary directory
  win_file:
    path: C:\Temp\iim
    state: directory
  register: tmp_dir

- name: Copy installer
  win_copy:
    src: "{{ iim_installer_path }}"
    dest: "{{ tmp_dir.path }}/"
  when: download_url is not defined
  register: iim_zip

- name: Download IIM installer
  win_get_url:
    url: "{{ download_url }}/{{ iim_installer_path }}"
    dest: "{{ tmp_dir.path }}/"
    headers: "{{ download_header }}"
  when: download_url is defined
  register: iim_zip

- name: Extract IIM installer
  win_unzip:
    src: "{{ iim_zip.dest }}"
    dest: "{{ tmp_dir.path }}"
    creates: "{{ tmp_dir.path }}/installc.exe"

- name: Run IIM installer
  win_command: installc.exe -acceptLicense -iD {{ iim_install_path }}
  args:
    chdir: "{{ tmp_dir.path }}"

- name: Delete temporary directory
  win_file:
    path: "{{ tmp_dir.path }}"
    state: absent
