---
- name: Create scripts directory
  file:
    path: /home/oracle/scripts
    mode: 0755
    state: directory

- name: Create start_all.sh
  copy:
    dest: /home/oracle/scripts/start_all.sh
    content: |
      #!/bin/bash
      . /opt/profile.d/oracle.sh
      export ORAENV_ASK=NO
      . oraenv
      export ORAENV_ASK=YES
      dbstart {{ oracle_home }}
    owner: oracle
    group: oinstall
    mode: 0755

- name: Create stop_all.sh
  copy:
    dest: /home/oracle/scripts/stop_all.sh
    content: |
      #!/bin/bash
      . /opt/profile.d/oracle.sh
      export ORAENV_ASK=NO
      . oraenv
      export ORAENV_ASK=YES
      dbshut {{ oracle_home }}
    owner: oracle
    group: oinstall
    mode: 0755

- name: "Create {{ profiled_path }}"
  file:
    path: "{{ profiled_path }}"
    mode: 0755
    state: directory

- name: "Create {{ profiled_path }}/oracle.sh"
  copy:
    dest: "{{ profiled_path }}/oracle.sh"
    content: |
      #!/bin/bash
      ORACLE_HOME={{ oracle_home }}
      export ORACLE_HOME
      ORACLE_BASE={{ oracle_base }}
      export ORACLE_BASE
      export PATH=$PATH:$ORACLE_HOME/bin
      ORACLE_SID={{ oracle_sid }}
      export ORACLE_SID
      if [ "$(whoami)" != "oracle" ]; then
        alias sqlplus='sudo -Eu oracle $ORACLE_HOME/bin/sqlplus'
        alias lsnrctl='sudo -Eu oracle $ORACLE_HOME/bin/lsnrctl'
      fi
    mode: 0755

- name: Create /opt/.profile
  copy:
    dest: /opt/.profile
    content: |
      #!/bin/bash
      PATH=.:$PATH

      if [ -e {{ profiled_path }} ]; then
        if [ "$PS1" ]; then
          ls -l {{ profiled_path }}/*.sh
        fi
        for lizard in {{ profiled_path }}/*.sh ; do
          . $lizard
        done
      fi

      LANG=en_US.ISO-8859-1
      umask 002
    mode: 0755

- name: Create /opt/Props
  file:
    path: /opt/Props
    state: directory

- name: Render Bootstrap.properties
  template:
    src: Bootstrap.properties.j2
    dest: /opt/Props/Bootstrap.properties

- name: Render BootstrapSeed.properties
  template:
    src: BootstrapSeed.properties.j2
    dest: /opt/Props/BootstrapSeed.properties
