---

- name: "Include v{{ oracle_version }}.yml variables"
  include_vars: "v{{ oracle_version }}.yml"

- name: Install Base version
  include_tasks: "{{ oracle_family }}_install.yml"
  when: base_version is defined

- name: Create and Configure DB
  include_tasks: configure.yml
  tags:
    - post

- name: Check if Patch already applied
  become: yes
  become_user: oracle
  # shell: "echo 'SELECT * FROM v$version;' | $ORACLE_HOME/bin/sqlplus / as sysdba | grep -i {{ oracle_version }}"
  shell: "$ORACLE_HOME/OPatch/opatch lspatches | grep -i {{ patch_number }}"
  register: oracle_version_status
  changed_when: False
  ignore_errors: True
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"

- name: Install Patch
  include_tasks: "patch.yml"
  when: patch_filename is defined and oracle_version_status.rc != 0

- name: Props and Profile
  include_tasks: "dot_profile.yml"
