---
- name: Create zip directory
  file:
    path: /tmp/repo-zips
    mode: 0755
    state: directory
  register: installer_dir

- name: Download IHS installers
  get_url:
    dest: "{{ installer_dir.path }}/{{ item }}"
    url: "{{ download_url }}/{{ ihs_installer_path }}/{{ item }}"
    headers: "{{ download_header }}"
  loop: "{{ ihs_installer_archive_list }}"
  when: download_url is defined

- name: Copy base installers
  copy:
    directory_mode: yes
    remote_src: no
    src: "{{ ihs_installer_path }}/"
    dest: "{{ installer_dir.path }}/"
  when: download_url is not defined

- name: Create IHS repo directories
  file:
    path: "/tmp/repo"
    state: directory

- name: Extract IHS installers
  unarchive:
    src: "{{ installer_dir.path }}/{{ item }}"
    dest: /tmp/repo/
    remote_src: yes
    creates: "/tmp/repo/disk{{ (index + 1) | string }}"
  loop: "{{ ihs_installer_archive_list }}"
  loop_control:
    index_var: index

- name: Install IHS
  iim_package:
    iim_path: "{{ iim_install_path }}"
    product_id: "com.ibm.websphere.IHS.{{ ihs_base_pid }}"
    path: "{{ ihs_install_path }}"
    repo: /tmp/repo
    properties:
      "user.ihs.httpPort": 80
    state: present
  when: "iim_info.packages | select('match', 'com.ibm.websphere.IHS.*') | list | length == 0"

- name: Install PLG
  iim_package:
    iim_path: "{{ iim_install_path }}"
    product_id: "com.ibm.websphere.PLG.{{ ihs_base_pid }}"
    path: "{{ plg_install_path }}"
    repo: /tmp/repo
    state: present
  when: "iim_info.packages | select('match', 'com.ibm.websphere.PLG.*') | list | length == 0"

- name: Install WCT
  iim_package:
    iim_path: "{{ iim_install_path }}"
    product_id: "com.ibm.websphere.WCT.{{ ihs_base_pid }}"
    path: "{{ wct_install_path }}"
    repo: /tmp/repo
    state: present
  when: "iim_info.packages | select('match', 'com.ibm.websphere.WCT.*') | list | length == 0"
