---
- name: Create zip directory
  file:
    path: /tmp/repo-zips
    mode: 0755
    state: directory
  register: installer_dir

- name: Download IHS installers
  get_url:
    dest: "{{ installer_dir.path }}/{{ item }}"
    url: "{{ download_url }}/{{ ihs_installer_path }}/{{ item }}"
    headers: "{{ download_header }}"
  loop: "{{ ihs_installer_archive_list }}"
  when: download_url is defined

- name: Copy base installers
  copy:
    directory_mode: yes
    remote_src: no
    src: "{{ ihs_installer_path }}/"
    dest: "{{ installer_dir.path }}/"
  when: download_url is not defined

- name: Create IHS base repo directories
  file:
    path: "/tmp/repo/{{ index }}"
    state: directory
  loop: "{{ ihs_installer_archive_list }}"
  loop_control:
    index_var: index

- name: Download Java repo
  get_url:
    dest: "{{ installer_dir.path }}/java-repo.zip"
    url: "{{ download_url }}/{{ ihs_java_zip_path }}"
    headers: "{{ download_header }}"
  when: download_url is defined

- name: Create Java repo directory
  file:
    path: /tmp/repo/java
    state: directory

- name: Extract IHS base installers
  unarchive:
    src: "{{ installer_dir.path }}/{{ item }}"
    dest: "/tmp/repo/{{ index }}"
    remote_src: yes
    creates: "/tmp/repo/{{ index }}/repository.config"
  loop: "{{ ihs_installer_archive_list }}"
  loop_control:
    index_var: index

- name: Extract Java installer
  unarchive:
    src: "{{ installer_dir.path }}/java-repo.zip"
    dest: /tmp/repo/java
    remote_src: yes
    creates: /tmp/repo/java/repository.config

- name: Build base repo list
  set_fact:
    repo_list: "{{ repo_list | default(['/tmp/repo/java']) + ['/tmp/repo/' + index|string]}}"
  loop: "{{ ihs_installer_archive_list }}"
  loop_control:
    index_var: index

- name: Install IHS
  iim_package:
    iim_path: "{{ iim_install_path }}"
    product_id:
      - "com.ibm.websphere.IHS.{{ ihs_pid.split('_') | first }}"
      - com.ibm.java.jdk.v8
    path: "{{ ihs_install_path }}"
    repo: "{{ repo_list }}"
    properties:
      "user.ihs.httpPort": 80
    state: present
  when: "iim_info.packages | select('match', 'com.ibm.websphere.IHS.*') | list | length == 0"

- name: Install PLG
  iim_package:
    iim_path: "{{ iim_install_path }}"
    product_id:
      - "com.ibm.websphere.PLG.{{ ihs_pid.split('_') | first }}"
      - com.ibm.java.jdk.v8
    path: "{{ plg_install_path }}"
    repo: "{{ repo_list }}"
    state: present
  when: "iim_info.packages | select('match', 'com.ibm.websphere.PLG.*') | list | length == 0"

- name: Install WCT
  iim_package:
    iim_path: "{{ iim_install_path }}"
    product_id:
      - "com.ibm.websphere.WCT.{{ ihs_pid.split('_') | first }}"
      - com.ibm.java.jdk.v8
    path: "{{ wct_install_path }}"
    repo: "{{ repo_list }}"
    state: present
  when: "iim_info.packages | select('match', 'com.ibm.websphere.WCT.*') | list | length == 0"
