---
# base installer values
oracle_rsp_filename: "install_{{ oracle_family }}R1.rsp.j2"
base_version: 12.1.0.2.0
base_installer:
  - linuxamd64_12102_database_1of2.zip
  - linuxamd64_12102_database_2of2.zip
