---
- name: "Check OPatch version matches {{ opatch_version }}"
  become: yes
  become_user: "{{ ohs_user }}"
  shell: "grep {{ opatch_version }} {{ ohs_home }}/OPatch/version.txt"
  ignore_errors: true
  register: opatch_status
  changed_when: False
  when: opatch_version is defined

# ==> install java
- name: Check if the Java download exists
  stat:
    path: "{{ ohs_installer_loc }}/java-repo.zip"
  register: stat_result

- name: Copy Java repo
  copy:
    src: "{{ java_zip_path }}"
    dest: "{{ ohs_installer_loc }}/java-repo.zip"
  when: download_url is not defined

- name: Download Java repo
  get_url:
    url: "{{ download_url }}/{{ java_zip_path }}"
    dest: "{{ ohs_installer_loc }}/java-repo.zip"
    headers: "{{ download_header }}"
  when: download_url is defined

- name: Extract Java installer
  unarchive:
    src: "{{ ohs_installer_loc }}/java-repo.zip"
    dest: "{{ jdk_folder }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create folder "/tmp/{{ ohs_version_folder }}"
  file:
    state: directory
    path: "/tmp/{{ ohs_version_folder }}"
    owner: "{{ ohs_user }}"
    group: "{{ ohs_group }}"

- name: "Download OPatch tool {{ opatch_filename_path }}"
  get_url:
    url: "{{ download_url }}/{{ opatch_filename_path }}"
    dest: "/tmp/{{ opatch_filename }}"
    owner: "{{ ohs_user }}"
    group: "{{ ohs_group }}"
    headers: "{{ download_header }}"
  when: opatch_filename_path is defined and download_url is defined

- name: "Copy OPatch tool {{ opatch_filename_path }}"
  copy:
    src: "{{ opatch_filename_path }}"
    dest: "/tmp/{{ opatch_filename }}"
    owner: "{{ ohs_user }}"
    group: "{{ ohs_group }}"
  when: download_url is not defined

- name: "Extract /tmp/{{ opatch_filename }}"
  unarchive:
    remote_src: yes
    src: "/tmp/{{ opatch_filename }}"
    dest: "{{ ohs_installer_loc }}"
    owner: "{{ ohs_user }}"
    group: "{{ ohs_group }}"
  when: opatch_version is defined and opatch_status.rc != 0

- name: Patch OPatch tool
  command: "{{ ohs_home }}/oracle_common/jdk/bin/java -jar {{ ohs_installer_loc }}/{{ opatch_folder }}/opatch_generic.jar -silent oracle_home={{ ohs_home }}"
  become: yes
  become_user: "{{ ohs_user }}"
  when: opatch_version is defined and opatch_status.rc != 0

- name: Create "{{ ohs_patch_path }}"
  file:
    path: "{{ ohs_patch_path }}"
    state: directory
    owner: "{{ ohs_user }}"
    group: "{{ ohs_group }}"
    mode: 0755

- name: "Download OHS Patches"
  get_url:
    url: "{{ download_url }}/{{ ohs_patch_path }}/{{ item.filename }}"
    dest: "{{ ohs_patch_path }}/{{ item.filename }}"
    owner: "{{ ohs_user }}"
    group: "{{ ohs_group }}"
    headers: "{{ download_header }}"
  loop: "{{ patches }}"
  when: download_url is defined

- name: "Copy OHS Patches"
  copy:
    src: "{{ ohs_patch_path }}/{{ item.filename }}"
    dest: "{{ ohs_patch_path }}"
    owner: "{{ ohs_user }}"
    group: "{{ ohs_group }}"
  loop: "{{ patches }}"
  when: download_url is not defined

- name: "Extract Patch {{ patch_filename }}"
  unarchive:
    remote_src: yes
    src: "{{ ohs_patch_path }}/{{ item.filename }}"
    dest: /tmp/
    owner: "{{ ohs_user }}"
    group: "{{ ohs_group }}"
  loop: "{{ patches }}"

- name: "Apply Patches"
  become: yes
  become_user: "{{ ohs_user }}"
  command: "{{ ohs_home }}/OPatch/opatch apply -silent"
  args:
    chdir: "/tmp/{{ item.number }}"
  loop: "{{ patches }}"
